export const INDUSTRIAL_ROOT_TITLE = 'Industrial'

export const INDUSTRIAL_TAXONOMY: Record<string, string[]> = {
  Manufacturing: [
    'Contract Manufacturing',
    'Low-Volume Manufacturing',
    'Custom Manufacturing',
    'Made-to-Order Manufacturing',
    'Precision Manufacturing',
    'Component Manufacturing',
    'Discrete Manufacturing',
    'OEM Manufacturing',
    'Process Manufacturing',
    'Industrial Manufacturing',
    'High-Volume Manufacturing',
    'B2B Manufacturing',
  ],
  'OEM & Component Manufacturing': [
    'OEM Manufacturers',
    'Engineered Components',
    'OEM Components',
    'Replacement Components',
    'Original Equipment Manufacturers',
    'Private Label Manufacturing',
    'Custom Components',
    'Tier 1 Suppliers',
    'Industrial Components',
    'Tier 2 Suppliers',
  ],
  'CNC & Precision Machining': [
    'CNC Machining',
    'High-Precision Machining',
    'CNC Milling',
    'Micro Machining',
    'CNC Turning',
    'EDM Machining',
    'Swiss CNC Machining',
    'Wire EDM',
    'Multi-Axis Machining',
    'Grinding',
    '3-Axis Machining',
    'Precision Grinding',
    '4-Axis Machining',
    'Tool & Die Manufacturing',
    '5-Axis Machining',
    'Jigs & Fixtures',
    'Precision Machining',
    'Prototype Machining',
  ],
  'Metal Fabrication': [
    'Metal Fabrication',
    'Aluminum Fabrication',
    'Custom Metal Fabrication',
    'Welded Fabrication',
    'Structural Steel Fabrication',
    'Industrial Metal Fabrication',
    'Heavy Metal Fabrication',
    'Architectural Metal Fabrication',
    'Sheet Metal Fabrication',
    'Metal Components',
    'Plate Fabrication',
    'Custom Metal Products',
    'Stainless Steel Fabrication',
  ],
  Welding: [
    'Industrial Welding',
    'Spot Welding',
    'Custom Welding',
    'Structural Welding',
    'Precision Welding',
    'Stainless Steel Welding',
    'Laser Welding',
    'Aluminum Welding',
    'TIG Welding',
    'Certified Welding',
    'MIG Welding',
    'AWS Welding',
    'Robotic Welding',
    'ASME Welding',
    'Resistance Welding',
  ],
  'Metal Forming & Stamping': [
    'Metal Stamping',
    'Metal Bending',
    'Precision Stamping',
    'Tube Bending',
    'Progressive Stamping',
    'Rotary Forming',
    'Deep Drawing',
    'Forging',
    'Metal Forming',
    'Open Die Forging',
    'Sheet Metal Forming',
    'Closed Die Forging',
    'Roll Forming',
    'Extrusion',
    'Press Brake Forming',
  ],
  'Casting & Molding': [
    'Metal Casting',
    'Blow Molding',
    'Investment Casting',
    'Compression Molding',
    'Die Casting',
    'Thermoforming',
    'Sand Casting',
    'Rotational Molding',
    'Permanent Mold Casting',
    'Mold Manufacturing',
    'Injection Molding',
    'Tooling',
    'Plastic Injection Molding',
  ],
  'Plastics & Polymer Manufacturing': [
    'Plastic Manufacturing',
    'Thermoplastic Manufacturing',
    'Plastic Injection Molding',
    'Polymer Manufacturing',
    'Plastic Extrusion',
    'Plastic Components',
    'Plastic Machining',
    'Plastic Assemblies',
    'Precision Plastic Manufacturing',
    'Plastic Prototyping',
    'Engineering Plastics',
  ],
  'Surface Finishing & Coatings': [
    'Industrial Coatings',
    'Thermal Spraying',
    'Metal Coatings',
    'Metal Finishing',
    'Powder Coating',
    'Surface Treatment',
    'Industrial Painting',
    'Passivation',
    'Plating',
    'Polishing',
    'Anodizing',
    'Corrosion Protection',
  ],
  'Heat Treatment & Material Processing': [
    'Heat Treatment',
    'Tempering',
    'Metal Heat Treatment',
    'Metallurgical Processing',
    'Vacuum Heat Treatment',
    'Material Testing',
    'Annealing',
    'Material Certification',
    'Hardening',
  ],
  'Assembly & Integration': [
    'Contract Assembly',
    'Subassembly Manufacturing',
    'Precision Assembly',
    'Final Assembly',
    'Mechanical Assembly',
    'Product Integration',
    'Electrical Assembly',
    'System Integration',
    'Electromechanical Assembly',
    'Industrial Assembly',
  ],
  'Electronics Manufacturing': [
    'Electronics Manufacturing',
    'Cable Assemblies',
    'Electronic Manufacturing Services (EMS)',
    'Wire Harness Manufacturing',
    'PCB Assembly',
    'Electromechanical Manufacturing',
    'Printed Circuit Board Manufacturing',
    'Embedded Electronics',
    'Electronic Components',
    'Electronic Product Manufacturing',
  ],
  'Industrial Automation & Robotics': [
    'Industrial Automation',
    'Machine Vision',
    'Manufacturing Automation',
    'Automated Inspection',
    'Production Automation',
    'Motion Control',
    'Robotics',
    'PLC Systems',
    'Industrial Robotics',
    'Industrial Control Systems',
    'Collaborative Robots',
    'SCADA',
    'Robotic Welding',
    'Automation System Integration',
    'Robotic Assembly',
  ],
  'Industrial Equipment & Machinery': [
    'Industrial Equipment',
    'Metalworking Equipment',
    'Industrial Machinery',
    'Industrial Systems',
    'Manufacturing Equipment',
    'Custom Industrial Equipment',
    'Processing Equipment',
    'Engineered Equipment',
    'Material Handling Equipment',
    'OEM Equipment',
    'Packaging Equipment',
  ],
  'Industrial Machinery & Machine Tools': [
    'CNC Machines',
    'Cutting Equipment',
    'Metalworking Machines',
    'Forming Equipment',
    'Machining Centers',
    'Welding Equipment',
    'Lathes',
    'Metal Fabrication Equipment',
    'Milling Machines',
    'Production Machinery',
    'Grinding Machines',
  ],
  'Industrial Automation Components': [
    'Sensors',
    'Power Transmission Components',
    'Actuators',
    'Bearings',
    'Motors',
    'Belts',
    'Drives',
    'Gears',
    'PLC Components',
    'Couplings',
    'Motion Control Systems',
    'Industrial Components',
    'Industrial Controllers',
  ],
  'Power Transmission': [
    'Power Transmission Equipment',
    'Gears',
    'Industrial Belts',
    'Couplings',
    'Conveyor Systems',
    'Chains',
    'Bearings',
    'Drive Systems',
    'Gearboxes',
    'Mechanical Power Transmission',
  ],
  'Material Handling': [
    'Material Handling Equipment',
    'Lifting Equipment',
    'Conveyors',
    'Hoists',
    'Conveyor Systems',
    'Cranes',
    'Automated Material Handling',
    'Palletizing Systems',
    'Warehouse Automation',
    'Industrial Material Transport',
    'Industrial Storage',
  ],
  'Packaging & Packaging Equipment': [
    'Industrial Packaging',
    'Palletizing',
    'Packaging Machinery',
    'Packaging Automation',
    'Packaging Equipment',
    'Flexible Packaging',
    'Filling Equipment',
    'Protective Packaging',
    'Labeling Equipment',
    'Industrial Packaging Systems',
  ],
  'Process Manufacturing': [
    'Chemical Manufacturing',
    'Specialty Chemicals',
    'Food Manufacturing',
    'Petrochemical Manufacturing',
    'Beverage Manufacturing',
    'Polymer Processing',
    'Pharmaceutical Manufacturing',
    'Industrial Materials',
    'Industrial Chemicals',
    'Process Equipment',
  ],
  'Chemical & Petrochemical': [
    'Chemical Manufacturing',
    'Chemical Equipment',
    'Specialty Chemicals',
    'Process Systems',
    'Industrial Chemicals',
    'Refining',
    'Petrochemicals',
    'Chemical Storage',
    'Chemical Processing',
  ],
  'Oil & Gas': [
    'Oil & Gas Equipment',
    'Refinery Equipment',
    'Oilfield Equipment',
    'Process Equipment',
    'Oilfield Services',
    'Pressure Vessels',
    'Pipeline Equipment',
    'Petrochemical Equipment',
    'Drilling Equipment',
  ],
  'Energy & Power Generation': [
    'Power Generation',
    'Solar Equipment',
    'Power Plant Equipment',
    'Wind Energy Equipment',
    'Electrical Equipment',
    'Energy Storage Systems',
    'Energy Equipment',
    'Grid Equipment',
    'Renewable Energy Equipment',
    'Power Transmission Equipment',
  ],
  'Pressure Vessels & Process Equipment': [
    'Pressure Vessel Manufacturing',
    'Heat Exchangers',
    'ASME Pressure Vessels',
    'Skid Systems',
    'Storage Tanks',
    'Process Skids',
    'Process Tanks',
    'Industrial Process Equipment',
    'Reactors',
  ],
  'HVAC & Climate Equipment': [
    'HVAC Manufacturing',
    'Ventilation Equipment',
    'HVAC Equipment',
    'Industrial Air Systems',
    'Industrial HVAC',
    'Filtration Systems',
    'Commercial HVAC',
    'Air Purification Systems',
    'Air Handling Equipment',
    'Temperature Control Systems',
  ],
  'Pumps, Valves & Fluid Handling': [
    'Industrial Pumps',
    'Fluid Handling Equipment',
    'Process Pumps',
    'Filtration Equipment',
    'Centrifugal Pumps',
    'Compressors',
    'Industrial Valves',
    'Fluid Processing Systems',
    'Flow Control',
  ],
  'Aerospace Manufacturing': [
    'Aerospace Manufacturing',
    'Aircraft Components',
    'Aerospace Components',
    'Aerospace Electronics',
    'Aerospace Machining',
    'Aerospace Materials',
    'Aerospace Metal Fabrication',
    'Aerospace & Defense Manufacturing',
    'Aerospace Assembly',
  ],
  'Automotive Manufacturing': [
    'Automotive Components',
    'Automotive Stamping',
    'Automotive OEM',
    'Automotive Plastics',
    'Automotive Tier 1 Suppliers',
    'Automotive Electronics',
    'Automotive Tier 2 Suppliers',
    'Automotive Assemblies',
    'Automotive Machining',
  ],
  'Medical Device Manufacturing': [
    'Medical Device Manufacturing',
    'Medical Assemblies',
    'Medical Components',
    'Medical Electronics',
    'Precision Medical Manufacturing',
    'Surgical Instruments',
    'Medical CNC Machining',
    'Life Sciences Manufacturing',
    'Medical Plastics',
  ],
  'Electrical & Electronic Equipment': [
    'Electrical Equipment Manufacturing',
    'Industrial Electronics',
    'Electronic Components',
    'Sensors',
    'Electrical Components',
    'Instrumentation',
    'Power Electronics',
    'Electrical Assemblies',
    'Control Systems',
  ],
  'Building Products & Materials': [
    'Building Products',
    'Specialty Building Products',
    'Building Materials',
    'Ventilated Facade Manufacturing',
    'Construction Products',
    'Facade Systems',
    'Architectural Products',
    'Aluminum Composite Panels',
    'Metal Building Products',
    'Aluminum Composite Panel Manufacturing',
    'Concrete Products',
    'Facade Installation',
    'Insulation Products',
    'Building Products Manufacturing',
    'Roofing Products',
    'Construction Materials Manufacturing',
    'Doors & Windows',
  ],
  'Food & Beverage Manufacturing': [
    'Food Manufacturing',
    'Food Packaging Equipment',
    'Food Processing',
    'Food Manufacturing Automation',
    'Beverage Manufacturing',
    'Industrial Food Systems',
    'Food Processing Equipment',
  ],
  'Pharmaceutical & Biotechnology Manufacturing': [
    'Pharmaceutical Manufacturing',
    'Cleanroom Equipment',
    'Biotechnology Manufacturing',
    'Laboratory Equipment',
    'Pharmaceutical Equipment',
    'Life Sciences Manufacturing',
    'Process Equipment',
  ],
  'Defense & Military Manufacturing': [
    'Defense Manufacturing',
    'Aerospace & Defense',
    'Defense Components',
    'Precision Defense Manufacturing',
    'Military Equipment',
    'Defense Supply Chain',
    'Defense Electronics',
  ],
  'Marine & Shipbuilding': [
    'Marine Manufacturing',
    'Marine Equipment',
    'Shipbuilding',
    'Marine Metal Fabrication',
    'Marine Components',
    'Marine Systems',
  ],
  'Agriculture & Agricultural Equipment': [
    'Agricultural Equipment',
    'Irrigation Equipment',
    'Agricultural Machinery',
    'Agricultural Automation',
    'Agricultural Components',
    'Agricultural Processing Equipment',
  ],
  'Mining & Heavy Industry': [
    'Mining Equipment',
    'Material Processing Equipment',
    'Mining Machinery',
    'Aggregate Processing Equipment',
    'Heavy Equipment',
    'Wear-Resistant Components',
    'Heavy Industrial Manufacturing',
  ],
  'MRO & Industrial Services': [
    'Maintenance, Repair & Operations (MRO)',
    'Industrial Installation',
    'Industrial Maintenance',
    'Equipment Service',
    'Equipment Maintenance',
    'Preventive Maintenance',
    'Industrial Repair',
    'Industrial Technical Services',
    'Field Service',
  ],
  'Engineering & Technical Services': [
    'Manufacturing Engineering',
    'Automation Engineering',
    'Mechanical Engineering',
    'Design Engineering',
    'Electrical Engineering',
    'Product Development',
    'Industrial Engineering',
    'Engineering Services',
    'Process Engineering',
    'Technical Consulting',
  ],
  'Industrial Distribution & Supply': [
    'Industrial Distributors',
    'Automation Distributors',
    'Equipment Distributors',
    'Industrial Supply',
    'Component Distributors',
    'Technical Distributors',
    'MRO Distributors',
    'Industrial Supply Chains',
    'Electrical Distributors',
  ],
  'Retail & Commercial Equipment Manufacturing': [
    'Retail Equipment Manufacturing',
    'Jewelry Store Equipment',
    'Retail Fixtures',
    'Commercial Display Equipment',
    'Store Fixtures',
    'Point-of-Sale Fixtures',
    'Custom Retail Equipment',
    'Custom Store Displays',
  ],
  'Laser Manufacturing': [
    'Laser Manufacturing',
    'Custom Laser Fabrication',
    'Laser Cutting',
    'Laser-Cut Metal Products',
    'Laser Processing',
    'Precision Laser Manufacturing',
  ],
  'Furniture Manufacturing': [
    'Furniture Manufacturing',
    'Salon Furniture',
    'Custom Furniture Manufacturing',
    'Educational Furniture',
    'Upholstered Furniture',
    'School Furniture',
    'Sofa Manufacturing',
    'Commercial Furniture',
    'Hospitality Furniture',
    'Contract Furniture',
    'Hotel Furniture',
  ],
  'Wood Manufacturing & Timber Construction': [
    'Wood Manufacturing',
    'Glulam House Manufacturing',
    'Timber Manufacturing',
    'Prefabricated Wooden Houses',
    'Engineered Wood Products',
    'Modular Wooden Buildings',
    'Wooden House Manufacturing',
    'Timber Construction',
    'Timber House Manufacturing',
    'Custom Wood Products',
  ],
  'Heating, Sauna & Fireplace Equipment': [
    'Heating Equipment',
    'Fireplace Manufacturing',
    'Heating Systems',
    'Stove Manufacturing',
    'Sauna Equipment',
    'Wood-Burning Stoves',
    'Sauna Manufacturing',
    'Heating Solutions',
  ],
  'Pneumatic Equipment': [
    'Pneumatic Equipment',
    'Communication Masts',
    'Pneumatic Systems',
    'Lighting Masts',
    'Pneumatic Telescopic Masts',
    'Emergency Service Masts',
    'Telescopic Masts',
    'Firefighting Masts',
    'Antenna Masts',
    'Industrial Telescopic Systems',
  ],
  'Telecommunications Equipment': [
    'Telecommunications Equipment',
    'Antenna Masts',
    'Communication Equipment',
    'Wireless Infrastructure',
    'Antenna Systems',
    'Communication Infrastructure',
  ],
  'Fire & Emergency Equipment': [
    'Firefighting Equipment',
    'Emergency Response Systems',
    'Emergency Equipment',
    'Fire & Rescue Infrastructure',
    'Rescue Equipment',
    'Emergency Service Equipment',
  ],
  'Industrial Lighting Equipment': [
    'Industrial Lighting Equipment',
    'High-Mast Lighting',
    'Lighting Masts',
    'Outdoor Industrial Lighting',
    'Floodlight Masts',
    'Lighting Systems',
  ],
  'Custom Industrial Manufacturing': [
    'Custom Manufacturing',
    'Design & Manufacturing',
    'Custom Industrial Products',
    'Engineering & Manufacturing',
    'Custom Equipment',
    'Design, Manufacturing & Installation',
    'Custom Components',
    'Turnkey Manufacturing Solutions',
  ],
}

export const expandIndustrialLongTitle = (title: string, parentTitle: string): string => {
  if (
    title.length >= 45 ||
    /manufactur|industrial|oem|cnc|fabricat|welding|assembly|automation|machinery|equipment|processing|engineering/i.test(
      title,
    )
  )
    return title
  return `${title} for industrial and manufacturing companies`
}
