export const TAXONOMY: Record<string, string[]> = {
  'Manufacturing Marketing Strategy': [
    'Manufacturing Marketing Strategy',
    'Industrial Marketing Strategy',
    'B2B Manufacturing Strategy',
    'Industrial Growth Strategy',
    'Go-to-Market Strategy',
    'Product Go-to-Market Strategy',
    'Market Expansion Strategy',
    'Market Entry Strategy',
    'Marketing Audit',
    'Marketing Planning',
    'Fractional CMO',
    'Marketing Transformation',
  ],
  'Brand Strategy & Positioning': [
    'Manufacturing Brand Strategy',
    'Industrial Brand Strategy',
    'Brand Positioning',
    'Industrial Brand Positioning',
    'Product Positioning',
    'Value Proposition',
    'Messaging Strategy',
    'Technical Product Messaging',
    'Competitive Positioning',
    'Brand Architecture',
    'Brand Identity',
    'Rebranding',
    'Brand Refresh',
    'Corporate Branding',
    'Manufacturer Brand Development',
  ],
  'Manufacturing SEO': [
    'Manufacturing SEO',
    'Industrial SEO',
    'B2B Manufacturing SEO',
    'Technical SEO',
    'On-Page SEO',
    'Technical SEO Audit',
    'Manufacturing Keyword Research',
    'Industrial Keyword Research',
    'Competitor SEO Analysis',
    'Search Intent Analysis',
    'Keyword Mapping',
    'Site Architecture',
    'Internal Linking',
    'Technical SEO Optimization',
    'Schema Markup',
    'Product Schema',
    'Product SEO',
    'Product Category SEO',
    'Industrial Product SEO',
    'Manufacturing Capability SEO',
    'Application SEO',
    'Specification SEO',
    'Material SEO',
    'Manufacturing Process SEO',
    'Certification SEO',
    'OEM SEO',
    'Distributor SEO',
    'International Manufacturing SEO',
    'Multilingual Manufacturing SEO',
    'Local Industrial SEO',
  ],
  'AI Search / AEO / GEO': [
    'Manufacturing AI SEO',
    'Industrial AI SEO',
    'AI Search Optimization',
    'AEO — Answer Engine Optimization',
    'GEO — Generative Engine Optimization',
    'AI Search Visibility',
    'AI Overview Optimization',
    'ChatGPT Search Optimization',
    'Perplexity Optimization',
    'LLM Content Optimization',
    'AI Citation Optimization',
    'Entity Optimization',
    'Technical Content for AI Search',
    'Product Content for AI Search',
    'Structured Data for AI',
  ],
  'Technical Content Marketing': [
    'Manufacturing Content Marketing',
    'Industrial Content Marketing',
    'Technical Content Marketing',
    'Engineering Content Marketing',
    'Technical Copywriting',
    'Technical Writing',
    'Product Content',
    'Product Page Content',
    'Capability Content',
    'Application Content',
    'Application Guides',
    'Technical Guides',
    'Specification Content',
    'Specification Pages',
    'Technical Articles',
    'Technical Blog Content',
    'Industry Content',
    'White Papers',
    'Technical White Papers',
    'eBooks',
    'Buyer Guides',
    'Industry Reports',
    'Research Reports',
    'Case Studies',
    'Solution Sheets',
    'Product Sheets',
    'Capability Sheets',
    'Technical FAQs',
    'Comparison Content',
    'Educational Content',
    'Thought Leadership',
    'Engineering Thought Leadership',
    'Product Demo Video',
    'Manufacturing Process Video',
  ],
  'Manufacturing Website Design & Development': [
    'Manufacturing Website Design',
    'Industrial Website Design',
    'B2B Manufacturing Website Design',
    'Industrial UX/UI',
    'Manufacturing Website Development',
    'Industrial Website Development',
    'Website Redesign',
    'Manufacturing Website Migration',
    'Industrial Website Architecture',
    'Product Catalog Website',
    'Digital Product Catalog',
    'Product Database',
    'Product Search',
    'Product Filtering',
    'Specification Database',
    'Technical Resource Library',
    'CAD File Library',
    'CAD Downloads',
    'Distributor Locator',
    'Dealer Locator',
    'Product Configurator',
    'RFQ Website',
    'RFQ Forms',
    'Quote Request System',
    'Distributor Portal',
    'Partner Portal',
  ],
  'Website Conversion & RFQ Optimization': [
    'Manufacturing CRO',
    'Industrial CRO',
    'B2B Conversion Optimization',
    'RFQ Conversion Optimization',
    'Quote Request Optimization',
    'Lead Form Optimization',
    'RFQ Form Optimization',
    'Product Page Conversion',
    'Product Catalog Conversion',
    'Landing Page Optimization',
    'Buyer Journey Optimization',
    'Technical Buyer UX',
    'Engineer Buyer UX',
    'Procurement Buyer UX',
    'Conversion Funnel Optimization',
  ],
  'Manufacturing Demand Generation': [
    'Manufacturing Demand Generation',
    'Industrial Demand Generation',
    'B2B Demand Generation',
    'Demand Generation Strategy',
    'Full-Funnel Demand Generation',
    'Pipeline Generation',
    'Pipeline Marketing',
    'Revenue Marketing',
    'Inbound Marketing',
    'Industrial Lead Generation',
    'Manufacturing Lead Generation',
    'Qualified Lead Generation',
    'RFQ Lead Generation',
    'Pipeline Development',
    'Lead Acquisition',
    'Lead Qualification',
  ],
  'Account-Based Marketing (ABM)': [
    'Manufacturing ABM',
    'Industrial ABM',
    'Account-Based Marketing',
    'Account-Based Demand Generation',
    'Target Account Marketing',
    'Named Account Marketing',
    'Strategic Account Marketing',
    'Target Account Identification',
    'Account Research',
    'Account Intelligence',
    'Account Targeting',
    'Account-Based Advertising',
    'LinkedIn ABM',
    'ABM Content',
    'ABM Landing Pages',
    'ABM Campaigns',
    'ABM Retargeting',
    'ABM Lead Nurturing',
    'ABM Sales Alignment',
  ],
  'Paid Search & Paid Media': [
    'Manufacturing PPC',
    'Industrial PPC',
    'B2B PPC',
    'Google Ads for Manufacturers',
    'Industrial Google Ads',
    'Manufacturing Search Advertising',
    'High-Intent Search Campaigns',
    'Product Search Advertising',
    'Specification Search Advertising',
    'Long-Tail Industrial PPC',
    'LinkedIn Advertising',
    'Manufacturing LinkedIn Ads',
    'Industrial LinkedIn Ads',
    'LinkedIn Account Targeting',
    'LinkedIn Matched Audiences',
    'Industrial Retargeting',
    'B2B Retargeting',
    'Display Advertising',
    'Programmatic Advertising',
  ],
  'Manufacturing Sales Enablement': [
    'Manufacturing Sales Enablement',
    'Industrial Sales Enablement',
    'Technical Sales Enablement',
    'Sales & Marketing Alignment',
    'Sales Content',
    'Technical Sales Content',
    'Sales Decks',
    'Product Presentations',
    'Product Sheets',
    'Capability Sheets',
    'One-Pagers',
    'Battlecards',
    'Competitive Battlecards',
    'Sales Guides',
    'Product Comparison Sheets',
    'ROI Calculators',
    'Sales Tools',
    'Proposal Support',
    'RFQ Support Content',
    'Lead Handoff',
    'Sales Engineering Content',
  ],
  'Distributor & Channel Marketing': [
    'Manufacturing Distributor Marketing',
    'Industrial Distributor Marketing',
    'Channel Marketing',
    'Channel Partner Marketing',
    'Dealer Marketing',
    'Distributor Lead Generation',
    'Distributor Enablement',
    'Distributor Content',
    'Distributor Campaigns',
    'Co-Branded Marketing',
    'Partner Marketing',
    'Dealer Enablement',
    'Distributor Recruitment',
    'Distributor Lead Routing',
    'Distributor Locator Marketing',
    'Channel Demand Generation',
  ],
  'Marketing Automation & CRM': [
    'Manufacturing Marketing Automation',
    'Industrial Marketing Automation',
    'Lead Nurturing',
    'Manufacturing Lead Nurturing',
    'Industrial Lead Nurturing',
    'Email Nurture',
    'Lead Scoring',
    'Lead Routing',
    'CRM Integration',
    'CRM Marketing',
    'HubSpot for Manufacturing',
    'HubSpot Implementation',
    'HubSpot Optimization',
    'Marketing-to-Sales Automation',
    'Sales Handoff Automation',
    'Pipeline Automation',
    'Lifecycle Marketing',
    'RFQ Follow-Up Automation',
    'Lead Re-Engagement',
    'Long-Cycle Nurturing',
  ],
  'Trade Show & Event Marketing': [
    'Manufacturing Trade Show Marketing',
    'Industrial Trade Show Marketing',
    'Trade Show Strategy',
    'Trade Show Campaigns',
    'Pre-Show Marketing',
    'Pre-Event Marketing',
    'Booth Traffic Generation',
    'Attendee Targeting',
    'Trade Show Lead Generation',
    'Event Lead Capture',
    'Post-Show Marketing',
    'Post-Event Nurturing',
    'Trade Show Retargeting',
    'Trade Show Email Campaigns',
    'Trade Show ABM',
    'Trade Show ROI Tracking',
    'Event-to-Pipeline Marketing',
  ],
  'Product Marketing': [
    'Manufacturing Product Marketing',
    'Industrial Product Marketing',
    'Product Marketing Strategy',
    'Product Positioning',
    'Product Messaging',
    'Product Launch Marketing',
    'New Product Launch',
    'Product Campaigns',
    'Product Content',
    'Product Page Strategy',
    'Product Catalog Marketing',
    'Product Education',
    'Product Demonstration',
    'Product Comparison',
    'Product Sales Enablement',
    'Product Lifecycle Marketing',
  ],
  'Industrial PR & Thought Leadership': [
    'Manufacturing PR',
    'Industrial PR',
    'B2B Industrial PR',
    'Technical PR',
    'Digital PR',
    'Trade Media PR',
    'Industry Media Relations',
    'Trade Publication Outreach',
    'Manufacturing Media Outreach',
    'Press Releases',
    'Executive Thought Leadership',
    'Technical Thought Leadership',
    'Industry Expert Positioning',
    'Industry Awards',
    'Award Campaigns',
    'Analyst Relations',
  ],
  'Industrial Link Building & Authority': [
    'Industrial Link Building',
    'Manufacturing Link Building',
    'Technical Link Building',
    'Trade Publication Outreach',
    'Industry Publication Outreach',
    'Digital PR Link Building',
    'Industrial Authority Building',
    'Manufacturer Brand Mentions',
    'Industry Citation Building',
  ],
  'Manufacturing Analytics & Attribution': [
    'Manufacturing Marketing Analytics',
    'Industrial Marketing Analytics',
    'Lead Attribution',
    'RFQ Attribution',
    'Pipeline Attribution',
    'Revenue Attribution',
    'Marketing ROI',
    'Campaign Attribution',
    'Lead Source Tracking',
    'RFQ Tracking',
    'CRM Attribution',
    'Conversion Tracking',
    'Pipeline Reporting',
    'Marketing Dashboards',
    'Revenue Reporting',
    'Marketing Performance Analysis',
  ],
  'Export & International Manufacturing Marketing': [
    'Manufacturing Export Marketing',
    'Industrial Export Marketing',
    'International Manufacturing Marketing',
    'Global Manufacturing Marketing',
    'International SEO',
    'Global SEO',
    'Multilingual Manufacturing Marketing',
    'International Lead Generation',
    'Export Lead Generation',
    'International Demand Generation',
    'Global Brand Positioning',
    'Market Entry Marketing',
    'International Distributor Marketing',
    'Distributor Recruitment Marketing',
  ],
  'Customer & Partner Marketing': [
    'Customer Marketing',
    'Customer Retention Marketing',
    'Customer Education',
    'Customer Engagement',
    'Existing Customer Marketing',
    'Cross-Sell Marketing',
    'Upsell Marketing',
    'Partner Marketing',
    'Channel Partner Engagement',
    'Distributor Engagement',
    'Customer Case Study Programs',
    'Customer Advocacy',
    'Review & Reputation Management',
  ],
}

const PARENT_HINTS: Record<string, string> = {
  'Manufacturing Marketing Strategy': 'for manufacturing companies',
  'Brand Strategy & Positioning': 'for industrial brands',
  'Manufacturing SEO': 'for manufacturing websites',
  'AI Search / AEO / GEO': 'for manufacturing brands',
  'Technical Content Marketing': 'for industrial buyers',
  'Manufacturing Website Design & Development': 'for manufacturers',
  'Website Conversion & RFQ Optimization': 'for manufacturing websites',
  'Manufacturing Demand Generation': 'for industrial demand',
  'Account-Based Marketing (ABM)': 'for manufacturing ABM programs',
  'Paid Search & Paid Media': 'for manufacturers',
  'Manufacturing Sales Enablement': 'for industrial sales teams',
  'Distributor & Channel Marketing': 'for manufacturer channels',
  'Marketing Automation & CRM': 'for manufacturing marketing teams',
  'Trade Show & Event Marketing': 'for industrial events',
  'Product Marketing': 'for manufacturing product lines',
  'Industrial PR & Thought Leadership': 'for manufacturers',
  'Industrial Link Building & Authority': 'for manufacturing sites',
  'Manufacturing Analytics & Attribution': 'for industrial marketing',
  'Export & International Manufacturing Marketing': 'for manufacturing exporters',
  'Customer & Partner Marketing': 'for manufacturers and partners',
}

export const cleanTitle = (raw: string): string =>
  raw
    .replace(/\s+NEW\s*$/i, '')
    .replace(/\s+/g, ' ')
    .trim()

const alreadyContextual = (title: string): boolean =>
  /manufactur|industrial|b2b|oem|rfq|hubspot|linkedin|chatgpt|perplexity|llm|geo|aeo/i.test(
    title,
  )

export const expandLongTitle = (title: string, parentTitle: string): string => {
  if (alreadyContextual(title) || title.length >= 45) return title
  const hint = PARENT_HINTS[parentTitle] || 'for manufacturing companies'
  return `${title} ${hint}`
}
