export const SOLUTIONS_ROOT_TITLE = 'Solutions'

export const SOLUTIONS_TAXONOMY: Record<string, string[]> = {
  'Lead Generation & New Business': [
    'B2B Lead Generation',
    'New Account Acquisition',
    'Qualified Lead Generation',
    'Strategic Account Acquisition',
    'New Customer Acquisition',
    'New Revenue Opportunities',
    'RFQ Generation',
    'New Business Opportunities',
    'High-Value Lead Generation',
  ],
  'Sales Growth': [
    'B2B Sales Growth',
    'Sales Pipeline Growth',
    'Manufacturing Sales Growth',
    'Sales Cycle Optimization',
    'Revenue Growth',
    'New Order Generation',
    'Conversion Rate Improvement',
  ],
  'Market Expansion': [
    'New Market Entry',
    'New Industry Expansion',
    'Geographic Expansion',
    'New Market Segment Development',
    'International Market Expansion',
    'U.S. Market Entry',
    'Export Market Development',
    'European Market Entry',
  ],
  'New Product Launch': [
    'Product Launch',
    'New Product Positioning',
    'New Product Introduction',
    'New Product Line Launch',
    'New Product Market Entry',
    'New Manufacturing Capability Launch',
    'New Product Demand',
  ],
  'Distributor & Channel Growth': [
    'Distributor Acquisition',
    'Channel Development',
    'Dealer Acquisition',
    'Channel Expansion',
    'Distributor Network Expansion',
    'Partner Acquisition',
    'Dealer Network Expansion',
    'Channel Sales Growth',
  ],
  'OEM & Contract Manufacturing Growth': [
    'OEM Lead Generation',
    'Contract Manufacturing Customer Acquisition',
    'Contract Manufacturing Leads',
    'Custom Manufacturing Lead Generation',
    'OEM Customer Acquisition',
    'Manufacturing Contract Acquisition',
    'OEM Partnership Development',
    'Supplier Opportunity Generation',
    'Contract Manufacturing Lead Generation',
  ],
  'Engineer & Specifier Reach': [
    'Engineer Engagement',
    'Specification Placement',
    'Architect Engagement',
    'Product Specification Growth',
    'Specifier Engagement',
    'Technical Buyer Acquisition',
    'Engineering Buyer Acquisition',
    'Design-In Opportunities',
  ],
  'Procurement & Buyer Reach': [
    'Procurement Buyer Acquisition',
    'Vendor Discovery',
    'Purchasing Department Engagement',
    'Procurement Opportunity Generation',
    'Industrial Buyer Acquisition',
    'Corporate Buyer Acquisition',
    'Supplier Discovery',
  ],
  'Brand, Market Position & Competitive Growth': [
    'Manufacturer Brand Positioning',
    'Competitive Advantage',
    'Industrial Brand Positioning',
    'Category Leadership',
    'Brand Awareness',
    'Market Leadership',
    'Industry Authority',
    'Competitive Visibility',
    'Manufacturer Reputation',
    'Market Share Growth',
    'Brand Trust',
    'Competitor Displacement',
    'Competitive Positioning',
    'Competitor Market Capture',
    'Market Differentiation',
  ],
  'Product & Application Growth': [
    'Product Demand Growth',
    'Application Market Expansion',
    'Product Line Growth',
    'Use-Case Development',
    'Product Application Expansion',
    'Industry Use-Case Expansion',
    'New Product Applications',
    'Product Use-Case Growth',
    'Market Expansion for Existing Products',
    'Application Awareness',
    'Cross-Industry Product Expansion',
    'Technical Application Education',
    'Product Category Expansion',
    'Solution-Based Product Growth',
    'New Application Development',
  ],
  'Digital Sales & Customer Acquisition Growth': [
    'Online Lead Generation',
    'E-commerce Growth',
    'Online Sales Growth',
    'Digital Market Expansion',
    'RFQ Growth',
    'Digital Product Discovery',
    'Quote Request Growth',
    'Digital Buyer Engagement',
    'Website Conversion Growth',
    'Digital Customer Experience',
    'Digital Customer Acquisition',
    'Digital Revenue Growth',
    'Product Catalog Conversion',
    'Digital Transformation for Growth',
  ],
  'Customer Growth & Retention': [
    'Customer Retention',
    'Cross-Selling',
    'Repeat Business',
    'Up-Selling',
    'Customer Expansion',
    'Existing Customer Growth',
    'Account Expansion',
    'Customer Lifetime Value Growth',
  ],
  'Complex B2B Sales': [
    'Long Sales Cycle Growth',
    'Complex Buying Journey',
    'Complex Product Sales',
    'Technical Buyer Conversion',
    'Technical Product Sales',
    'Enterprise Customer Acquisition',
    'High-Consideration Purchase Growth',
    'Enterprise Account Acquisition',
    'Multi-Stakeholder Buyer Engagement',
  ],
  'Manufacturing Capability Growth': [
    'Manufacturing Capability Promotion',
    'Production Technology Promotion',
    'Production Capacity Promotion',
    'Manufacturing Expertise Promotion',
    'Engineering Capability Promotion',
    'Facility Capability Promotion',
    'Custom Manufacturing Promotion',
    'Certification & Capability Promotion',
  ],
  'Customer & Market Education': [
    'Product Education',
    'Engineer Education',
    'Technical Education',
    'Procurement Education',
    'Application Education',
    'Technical Decision Support',
    'Buyer Education',
    'Manufacturing Knowledge Resources',
  ],
}

export const expandSolutionsLongTitle = (title: string, _parentTitle: string): string => {
  if (
    title.length >= 45 ||
    /manufactur|growth|lead|sales|market|customer|digital|b2b|oem|rfq|brand|product|channel|procurement|engineer|retention|revenue/i.test(
      title,
    )
  )
    return title
  return `${title} for manufacturing and industrial companies`
}
