export const TECHNOLOGY_ROOT_TITLE = 'Technology'

export const TECHNOLOGY_TAXONOMY: Record<string, string[]> = {
  'Industrial Automation & Control Systems': [
    'Industrial Automation',
    'PLC Systems',
    'Factory Automation',
    'SCADA',
    'Production Automation',
    'HMI Systems',
    'Process Automation',
    'Motion Control',
    'Automation Systems',
    'Industrial Control Systems',
    'Control Systems',
  ],
  Robotics: [
    'Industrial Robotics',
    'Robotic Handling',
    'Collaborative Robots',
    'Automated Palletizing',
    'Robotic Welding',
    'Autonomous Mobile Robots',
    'Robotic Assembly',
    'Robotic Machine Tending',
  ],
  'CNC & Advanced Machining': [
    'CNC Machining',
    'Multi-Axis Machining',
    'CNC Milling',
    'Swiss Machining',
    'CNC Turning',
    'EDM',
    '3-Axis Machining',
    'Wire EDM',
    '4-Axis Machining',
    'Precision Machining',
    '5-Axis Machining',
  ],
  'Additive Manufacturing': [
    '3D Printing',
    'Rapid Prototyping',
    'Industrial 3D Printing',
    'Rapid Manufacturing',
    'Metal 3D Printing',
    'Direct Metal Laser Sintering',
    'Polymer 3D Printing',
    'Selective Laser Sintering',
    'Additive Manufacturing',
  ],
  'Laser & Advanced Manufacturing': [
    'Laser Cutting',
    'Laser Processing',
    'Laser Welding',
    'Laser Manufacturing',
    'Laser Engraving',
    'Fiber Laser Technology',
    'Laser Marking',
    'Precision Laser Manufacturing',
  ],
  'Machine Vision & Automated Inspection': [
    'Industrial Machine Vision',
    'Vision-Guided Robotics',
    'Computer Vision',
    'Defect Detection',
    'Automated Visual Inspection',
    'Measurement Systems',
    'Quality Inspection',
    'Non-Destructive Testing Technology',
    'Optical Inspection',
    'Statistical Process Control',
  ],
  'Industrial IoT (IIoT)': [
    'Industrial IoT',
    'Industrial Sensor Networks',
    'IIoT',
    'Remote Monitoring',
    'Connected Manufacturing',
    'Equipment Monitoring',
    'Connected Machines',
    'Condition Monitoring',
  ],
  'Industry 4.0, Smart Factory & Digital Manufacturing': [
    'Industry 4.0',
    'Manufacturing Digitization',
    'Smart Manufacturing',
    'Digital Manufacturing',
    'Smart Factory',
    'Paperless Manufacturing',
    'Connected Factory',
    'Digital Workflows',
    'Intelligent Manufacturing',
    'Automated Production',
    'Digital Transformation',
  ],
  'Manufacturing Software': [
    'Manufacturing Software',
    'Production Management Software',
    'Manufacturing ERP',
    'Quality Management Software',
    'Manufacturing Execution Systems (MES)',
    'Maintenance Management Software',
    'Manufacturing Planning Software',
    'Supply Chain Software',
  ],
  'Digital Twin & Simulation': [
    'Digital Twins',
    'Process Simulation',
    'Manufacturing Simulation',
    'Product Simulation',
    'Production Simulation',
    'Virtual Commissioning',
    'Factory Simulation',
    'Digital Factory',
  ],
  'Artificial Intelligence & Predictive Maintenance': [
    'AI in Manufacturing',
    'AI Process Optimization',
    'Machine Learning',
    'Generative AI for Manufacturing',
    'Predictive Analytics',
    'Failure Prediction',
    'Predictive Maintenance',
    'Asset Performance Management',
    'Condition-Based Maintenance',
    'Industrial Diagnostics',
    'AI Quality Inspection',
    'Machine Health Monitoring',
    'AI Production Optimization',
  ],
  'Industrial Data & Analytics': [
    'Manufacturing Analytics',
    'Production Monitoring',
    'Industrial Data',
    'Performance Analytics',
    'Production Data',
    'Manufacturing KPIs',
    'Machine Data',
    'Real-Time Manufacturing Data',
    'Operational Analytics',
  ],
  'Industrial Connectivity & Edge Computing': [
    'Industrial Networking',
    'Edge Computing',
    'Industrial Ethernet',
    'Edge Devices',
    'Wireless Industrial Networks',
    'Edge Analytics',
    'Machine-to-Machine Communication',
    'Edge AI',
    'Industrial Communication',
    'Real-Time Edge Processing',
    'Industrial Gateways',
  ],
  'Sensors & Instrumentation': [
    'Industrial Sensors',
    'Proximity Sensors',
    'Temperature Sensors',
    'Position Sensors',
    'Pressure Sensors',
    'Industrial Instrumentation',
    'Flow Sensors',
  ],
  'Warehouse & Logistics Technology': [
    'Warehouse Automation',
    'Warehouse Robotics',
    'Automated Storage and Retrieval Systems (AS/RS)',
    'Automated Conveyors',
    'Automated Material Handling',
    'Inventory Automation',
    'Smart Warehouses',
    'Logistics Automation',
  ],
  'Supply Chain Technology': [
    'Supply Chain Management Technology',
    'Manufacturing Planning',
    'Supply Chain Analytics',
    'Inventory Management Technology',
    'Supply Chain Automation',
    'Procurement Technology',
    'Digital Supply Chain',
    'Production Planning Systems',
  ],
  'Manufacturing Cybersecurity': [
    'Industrial Cybersecurity',
    'SCADA Security',
    'OT Security',
    'PLC Security',
    'Operational Technology Security',
    'Factory Cybersecurity',
    'Industrial Network Security',
    'Manufacturing Data Security',
  ],
  'Digital Product Development': [
    'CAD',
    '3D CAD',
    'CAM',
    'Digital Prototyping',
    'CAE',
    'Product Lifecycle Management (PLM)',
    'Product Design Software',
    'Engineering Software',
  ],
  'Advanced Materials Technology': [
    'Advanced Materials',
    'Carbon Fiber',
    'Composite Materials',
    'Metal Alloys',
    'Advanced Polymers',
    'Smart Materials',
    'Engineering Plastics',
    'High-Performance Materials',
  ],
}

export const expandTechnologyLongTitle = (title: string, _parentTitle: string): string => {
  if (
    title.length >= 45 ||
    /manufactur|industrial|technology|automation|robotic|cnc|laser|software|digital|ai|iot|edge|sensor|cyber|cad|cam|plm|3d|mes|erp|scada|plc/i.test(
      title,
    )
  )
    return title
  return `${title} for manufacturing and industrial technology`
}
