/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    posts: Post;
    'case-studies': CaseStudy;
    services: Service;
    testimonials: Testimonial;
    media: Media;
    categories: Category;
    'case-study-categories': CaseStudyCategory;
    'site-categories': SiteCategory;
    users: User;
    redirects: Redirect;
    forms: Form;
    'form-submissions': FormSubmission;
    search: Search;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    categories: {
      relatedPosts: 'posts';
    };
    'case-study-categories': {
      relatedCaseStudies: 'case-studies';
    };
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'media';
    };
  };
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    'case-studies': CaseStudiesSelect<false> | CaseStudiesSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    'case-study-categories': CaseStudyCategoriesSelect<false> | CaseStudyCategoriesSelect<true>;
    'site-categories': SiteCategoriesSelect<false> | SiteCategoriesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
    'case-studies-archive': CaseStudiesArchive;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'case-studies-archive': CaseStudiesArchiveSelect<false> | CaseStudiesArchiveSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * Длинный основной заголовок страницы. Используется как H1.
   */
  pageLongTitle: string;
  hero: {
    type: 'none' | 'highImpact' | 'mediumImpact' | 'lowImpact';
    richText?: {
      [k: string]: unknown;
    } | null;
    links?:
      | {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?:
              | ({
                  relationTo: 'pages';
                  value: number | Page;
                } | null)
              | ({
                  relationTo: 'posts';
                  value: number | Post;
                } | null);
            url?: string | null;
            label: string;
            /**
             * Choose how the link should be rendered.
             */
            appearance?: ('default' | 'outline') | null;
          };
          id?: string | null;
        }[]
      | null;
    media?: (number | null) | Media;
  };
  layout: (CallToActionBlock | ContentBlock | MediaBlock | ArchiveBlock | FormBlock | PagePreviewBlock | CodeBlock)[];
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  /**
   * Короткий сегмент URL сразу после домена, например: about, services, manufacturing. Задаётся вручную и не зависит от заголовка.
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * Длинный основной заголовок поста. Используется как H1.
   */
  postLongTitle: string;
  layout: (
    | PostPreviewBlock
    | PostContentBlock
    | PostContentTitleBlock
    | PostVideoBlock
    | PostGalleryBlock
    | PostCommentsBlock
    | PostFAQBlock
    | CodeBlock
    | CallToActionBlock
    | MediaBlock
    | ArchiveBlock
  )[];
  hero: {
    type: 'none' | 'highImpact' | 'mediumImpact' | 'lowImpact';
    richText?: {
      [k: string]: unknown;
    } | null;
    links?:
      | {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?:
              | ({
                  relationTo: 'pages';
                  value: number | Page;
                } | null)
              | ({
                  relationTo: 'posts';
                  value: number | Post;
                } | null);
            url?: string | null;
            label: string;
            /**
             * Choose how the link should be rendered.
             */
            appearance?: ('default' | 'outline') | null;
          };
          id?: string | null;
        }[]
      | null;
    media?: (number | null) | Media;
  };
  relatedPosts?: (number | Post)[] | null;
  /**
   * Used in the post URL: /blog/{primary-category-slug}/{post-slug}. Browse the tree and pick one category.
   */
  primary_category: number | Category;
  /**
   * Blog topics for this article. Browse the tree and add one or more categories.
   */
  categories?: (number | Category)[] | null;
  /**
   * Site taxonomy nodes for this post (independent from Blog Categories). Browse the tree and add one or more.
   */
  site_categories?: (number | SiteCategory)[] | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  authors?: (number | User)[] | null;
  populatedAuthors?:
    | {
        id?: string | null;
        name?: string | null;
      }[]
    | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PostPreviewBlock".
 */
export interface PostPreviewBlock {
  postPreviewTitle?: string | null;
  postPreviewText?: {
    [k: string]: unknown;
  } | null;
  postPreviewImage?: (number | null) | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'postPreviewBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  caption?: {
    [k: string]: unknown;
  } | null;
  folder?: (number | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlarge?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: number;
  name: string;
  folder?: (number | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: number | FolderInterface;
        }
      | {
          relationTo?: 'media';
          value: number | Media;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folderType?: 'media'[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PostContentBlock".
 */
export interface PostContentBlock {
  columns?:
    | {
        size?: ('oneThird' | 'half' | 'twoThirds' | 'full') | null;
        richText?: {
          [k: string]: unknown;
        } | null;
        enableLink?: boolean | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'postContentBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PostContentTitleBlock".
 */
export interface PostContentTitleBlock {
  /**
   * Дополнительный заголовок для Content. При выводе используется как H2.
   */
  postContentTitle?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'postContentTitleBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PostVideoBlock".
 */
export interface PostVideoBlock {
  postVideoTitle?: string | null;
  postVideoDescription?: {
    [k: string]: unknown;
  } | null;
  /**
   * Код встраивания видео, например YouTube embed. Не файл.
   */
  postVideoCode?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'postVideoBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PostGalleryBlock".
 */
export interface PostGalleryBlock {
  postGalleryTitle?: string | null;
  /**
   * До 20 изображений из Media. Можно выбрать существующие или загрузить новые.
   */
  postGalleryImages?: (number | Media)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'postGalleryBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PostCommentsBlock".
 */
export interface PostCommentsBlock {
  postCommentTitle?: string | null;
  postCommentText?: {
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'postCommentsBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PostFAQBlock".
 */
export interface PostFAQBlock {
  postFAQTitle?: string | null;
  postFAQText?: {
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'postFAQBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeBlock".
 */
export interface CodeBlock {
  language?: ('typescript' | 'javascript' | 'css') | null;
  code: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'code';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  richText?: {
    [k: string]: unknown;
  } | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  media: number | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock".
 */
export interface ArchiveBlock {
  introContent?: {
    [k: string]: unknown;
  } | null;
  populateBy?: ('collection' | 'selection') | null;
  relationTo?: 'posts' | null;
  categories?: (number | Category)[] | null;
  limit?: number | null;
  selectedDocs?:
    | {
        relationTo: 'posts';
        value: number | Post;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'archive';
}
/**
 * Thematic categories for blog articles. Not a substitute for Services, Industries, or Solutions.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  /**
   * Public H1. Must differ from a Case Study Category with the same short title. Insights/articles intent, not project work.
   */
  category_long_title: string;
  /**
   * Visible intro on the public category page. Describe articles and insights, not case studies. About 400 characters.
   */
  category_description?: {
    [k: string]: unknown;
  } | null;
  /**
   * Image for category cards and archive pages.
   */
  category_image?: (number | null) | Media;
  /**
   * Posts linked through the existing Categories field on Post.
   */
  relatedPosts?: {
    docs?: (number | Post)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * Дополнительный контент под списком постов категории.
   */
  layout?: (CallToActionBlock | ContentBlock | MediaBlock | ArchiveBlock | FormBlock | CodeBlock)[] | null;
  /**
   * Public search metadata. Must differ from the equivalent Case Study Category when the short title is shared.
   */
  meta?: {
    title?: string | null;
    description?: string | null;
  };
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  parent?: (number | null) | Category;
  breadcrumbs?:
    | {
        doc?: (number | null) | Category;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  columns?:
    | {
        size?: ('oneThird' | 'half' | 'twoThirds' | 'full') | null;
        richText?: {
          [k: string]: unknown;
        } | null;
        enableLink?: boolean | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock".
 */
export interface FormBlock {
  form: number | Form;
  enableIntro?: boolean | null;
  introContent?: {
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'formBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        message?: {
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Internal site structure tree (parent/child). Used for taxonomy and relationships — not public pages.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-categories".
 */
export interface SiteCategory {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  parent?: (number | null) | SiteCategory;
  breadcrumbs?:
    | {
        doc?: (number | null) | SiteCategory;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PagePreviewBlock".
 */
export interface PagePreviewBlock {
  pagePreviewTitle?: string | null;
  pagePreviewText?: {
    [k: string]: unknown;
  } | null;
  pagePreviewImage?: (number | null) | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'pagePreviewBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies".
 */
export interface CaseStudy {
  id: number;
  title: string;
  /**
   * Main case study heading. Used as H1 on the frontend.
   */
  case_study_long_title: string;
  layout: (
    | CaseStudyPreviewBlock
    | CaseStudyContentBlock
    | CaseStudyContentTitleBlock
    | CaseStudyVideoBlock
    | CaseStudyGalleryBlock
    | CaseStudyCommentsBlock
    | CaseStudyFAQBlock
    | CodeBlock
    | CallToActionBlock
    | MediaBlock
    | ArchiveBlock
  )[];
  /**
   * Optional logo of the company in this Case Study. Separate from Preview Image and hero photography. Displayed with original proportions, never cropped.
   */
  company_logo?: (number | null) | Media;
  /**
   * Production core of the client. Content fields only — use Case Study Categories for Technology taxonomy.
   */
  manufacturingProfile?: {
    /**
     * Production capacity, equipment, operations, volumes, and full/partial cycle.
     */
    productionCapabilities?: {
      [k: string]: unknown;
    } | null;
    /**
     * Real products or product groups manufactured by the client.
     */
    products?: {
      [k: string]: unknown;
    } | null;
    /**
     * Materials used in production (metal, steel, wood, acrylic, composites, etc.).
     */
    materials?: {
      [k: string]: unknown;
    } | null;
    /**
     * Industries and use-cases for the products (construction, facades, retail, HoReCa, etc.).
     */
    applications?: {
      [k: string]: unknown;
    } | null;
  };
  businessChallenge?: {
    /**
     * What the business looked like before the engagement.
     */
    initialState?: {
      [k: string]: unknown;
    } | null;
    /**
     * The core set of business problems.
     */
    challenge?: {
      [k: string]: unknown;
    } | null;
    /**
     * Project goals and KPIs.
     */
    goals?: {
      [k: string]: unknown;
    } | null;
  };
  /**
   * How a complex plant is broken into distinct commercial directions. Do not duplicate products/applications here.
   */
  nicheSegmentation?:
    | {
        name: string;
        /**
         * Essence of the direction and positioning.
         */
        description?: {
          [k: string]: unknown;
        } | null;
        /**
         * Promotion strategy for this specific direction.
         */
        marketingApproach?: {
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Overall digital infrastructure (website, landings, CRM, analytics, ads, messengers).
   */
  digitalEcosystem?: {
    [k: string]: unknown;
  } | null;
  /**
   * Site structure, URL architecture, landing pages, navigation, and content hierarchy.
   */
  websiteArchitecture?: {
    [k: string]: unknown;
  } | null;
  /**
   * Semantic structure, entity links, internal hubs and clusters.
   */
  semanticArchitecture?: {
    [k: string]: unknown;
  } | null;
  marketingStrategy?: {
    /**
     * Combined SEO, semantics, content, and internal linking strategy.
     */
    seoAndContentStrategy?: {
      [k: string]: unknown;
    } | null;
    /**
     * Conversion layer: forms, WhatsApp, quote/calc forms, proposals, CRM attribution.
     */
    leadGenMechanism?: {
      [k: string]: unknown;
    } | null;
    paidAdvertising?:
      | {
          channel: 'google_ads' | 'microsoft_ads' | 'yandex_direct' | 'meta_ads' | 'linkedin_ads' | 'other';
          strategy?: {
            [k: string]: unknown;
          } | null;
          campaignStructure?: {
            [k: string]: unknown;
          } | null;
          results?: {
            [k: string]: unknown;
          } | null;
          id?: string | null;
        }[]
      | null;
    socialMedia?:
      | {
          channel: 'linkedin' | 'facebook' | 'instagram' | 'youtube' | 'tiktok' | 'telegram' | 'other';
          strategy?: {
            [k: string]: unknown;
          } | null;
          content?: {
            [k: string]: unknown;
          } | null;
          results?: {
            [k: string]: unknown;
          } | null;
          id?: string | null;
        }[]
      | null;
  };
  aiSearchOptimization?: {
    /**
     * Brand authority, E-E-A-T signals, external mentions, reviews, expert materials and publications.
     */
    brandAuthorityAndTrust?: {
      [k: string]: unknown;
    } | null;
    /**
     * Company and products as interconnected entities for AI search (ChatGPT, Perplexity, Gemini, Google SGE).
     */
    entityAndGeoStructure?: {
      [k: string]: unknown;
    } | null;
  };
  /**
   * Main stages of the engagement.
   */
  implementationProcess?: {
    [k: string]: unknown;
  } | null;
  timeline?:
    | {
        period?: string | null;
        title?: string | null;
        description?: {
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Final client outcome in narrative form.
   */
  resultsSummary?: {
    [k: string]: unknown;
  } | null;
  metrics?:
    | {
        /**
         * Example: "+140%", "3.2x"
         */
        value: string;
        /**
         * Example: "Growth of qualified leads"
         */
        label: string;
        description?: {
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Concrete examples of manufactured products / plant projects.
   */
  projectsShowcase?:
    | {
        projectName: string;
        description?: {
          [k: string]: unknown;
        } | null;
        image?: (number | null) | Media;
        /**
         * Optional external or internal project URL.
         */
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Team takeaways, engineering/marketing hacks and challenges.
   */
  expertInsight?: {
    [k: string]: unknown;
  } | null;
  /**
   * Structured proof quote. Free-form comments remain available via the existing Case Study Comments layout block.
   */
  clientTestimonial?: {
    quote?: {
      [k: string]: unknown;
    } | null;
    author?: string | null;
    position?: string | null;
    company?: string | null;
  };
  hero: {
    type: 'none' | 'highImpact' | 'mediumImpact' | 'lowImpact';
    richText?: {
      [k: string]: unknown;
    } | null;
    links?:
      | {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?:
              | ({
                  relationTo: 'pages';
                  value: number | Page;
                } | null)
              | ({
                  relationTo: 'posts';
                  value: number | Post;
                } | null);
            url?: string | null;
            label: string;
            /**
             * Choose how the link should be rendered.
             */
            appearance?: ('default' | 'outline') | null;
          };
          id?: string | null;
        }[]
      | null;
    media?: (number | null) | Media;
  };
  relatedCaseStudies?: (number | CaseStudy)[] | null;
  /**
   * Used in the case study URL: /case-studies/{category-slug}/{case-study-slug}. Browse the tree and pick one category.
   */
  primary_case_study_category: number | CaseStudyCategory;
  /**
   * Thematic case study categories. Browse the tree and add one or more.
   */
  case_study_categories?: (number | CaseStudyCategory)[] | null;
  /**
   * Site taxonomy nodes (independent from Case Study Categories). Browse the tree and add one or more.
   */
  site_categories?: (number | SiteCategory)[] | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  /**
   * When enabled, this Case Study can appear in the Featured Case Studies block on the homepage.
   */
  featured?: boolean | null;
  /**
   * Controls the priority and display order of this Case Study. Lower numbers appear first.
   */
  displayOrder?: number | null;
  /**
   * Engagement duration for this Case Study.
   */
  duration?:
    | (
        | '6_months'
        | '1_years'
        | '2_years'
        | '3_years'
        | '4_years'
        | '5_years'
        | '6_years'
        | '7_years'
        | '8_years'
        | '9_years'
        | '10_years'
        | '11_years'
        | '12_years'
        | '13_years'
        | '14_years'
        | '15_years'
        | '16_years'
        | '17_years'
        | '18_years'
        | '19_years'
        | '20_years'
      )
    | null;
  publishedAt?: string | null;
  authors?: (number | User)[] | null;
  populatedAuthors?:
    | {
        id?: string | null;
        name?: string | null;
      }[]
    | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CaseStudyPreviewBlock".
 */
export interface CaseStudyPreviewBlock {
  case_study_preview_title?: string | null;
  case_study_preview_text?: {
    [k: string]: unknown;
  } | null;
  case_study_preview_image?: (number | null) | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'csPreview';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CaseStudyContentBlock".
 */
export interface CaseStudyContentBlock {
  columns?:
    | {
        size?: ('oneThird' | 'half' | 'twoThirds' | 'full') | null;
        richText?: {
          [k: string]: unknown;
        } | null;
        enableLink?: boolean | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'csContent';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CaseStudyContentTitleBlock".
 */
export interface CaseStudyContentTitleBlock {
  /**
   * Additional content heading. Rendered as H2.
   */
  case_study_content_title?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'csContentTitle';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CaseStudyVideoBlock".
 */
export interface CaseStudyVideoBlock {
  case_study_video_title?: string | null;
  case_study_video_description?: {
    [k: string]: unknown;
  } | null;
  /**
   * Embed code (e.g. YouTube iframe). Not a video file upload.
   */
  case_study_video_code?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'csVideo';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CaseStudyGalleryBlock".
 */
export interface CaseStudyGalleryBlock {
  /**
   * Section heading. Defaults to Gallery. Change it for a specific set, for example Manufacturing Gallery or Before & After.
   */
  case_study_gallery_title?: string | null;
  /**
   * Up to 20 images from Media.
   */
  case_study_gallery_images?: (number | Media)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'csGallery';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CaseStudyCommentsBlock".
 */
export interface CaseStudyCommentsBlock {
  /**
   * Section heading. Falls back to "Discussion" when empty.
   */
  case_study_comment_title?: string | null;
  /**
   * Optional lead-in above the thread. Individual entries go in Discussion.
   */
  case_study_comment_text?: {
    [k: string]: unknown;
  } | null;
  comments?:
    | {
        author: string;
        /**
         * Job title or industry perspective.
         */
        role?: string | null;
        date?: string | null;
        /**
         * Parent/reply relationship: 0 is a new top-level branch. Depth N replies to the nearest preceding comment at depth N-1. The frontend builds the tree from this, not from visual indent.
         */
        depth?: number | null;
        /**
         * Marks the entry as an answer from the site expert.
         */
        isExpert?: boolean | null;
        body: {
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'csComments';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CaseStudyFAQBlock".
 */
export interface CaseStudyFAQBlock {
  /**
   * Section heading, e.g. "Frequently Asked Questions About Laser Made". Falls back to a generic heading when empty.
   */
  case_study_faq_title?: string | null;
  /**
   * Optional lead-in above the questions. Individual questions go in Questions.
   */
  case_study_faq_text?: {
    [k: string]: unknown;
  } | null;
  /**
   * Each entry renders as one accordion row.
   */
  items?:
    | {
        question: string;
        answer: {
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'csFAQ';
}
/**
 * Thematic categories for case studies. Separate from Blog Categories.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-study-categories".
 */
export interface CaseStudyCategory {
  id: number;
  title: string;
  /**
   * Public H1. Must differ from a Post Category with the same short title. Case studies/projects intent, not articles.
   */
  case_study_long_title: string;
  /**
   * Visible intro on the public category page. Describe real projects and implementations. About 400 characters.
   */
  case_study_description?: {
    [k: string]: unknown;
  } | null;
  /**
   * Image for category cards and archive pages.
   */
  case_study_image?: (number | null) | Media;
  /**
   * Case studies linked through Case Study Categories.
   */
  relatedCaseStudies?: {
    docs?: (number | CaseStudy)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * Additional content below the case study list for this category.
   */
  layout?: (CallToActionBlock | ContentBlock | MediaBlock | ArchiveBlock | FormBlock | CodeBlock)[] | null;
  /**
   * Public search metadata. Must differ from the equivalent Post Category when the short title is shared.
   */
  meta?: {
    title?: string | null;
    description?: string | null;
  };
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  parent?: (number | null) | CaseStudyCategory;
  breadcrumbs?:
    | {
        doc?: (number | null) | CaseStudyCategory;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  /**
   * Internal document title.
   */
  title: string;
  /**
   * SEO/content heading used as H1. Falls back to the internal title when empty.
   */
  service_long_title?: string | null;
  /**
   * Short title for cards, archives and related-service lists. Not the page H1.
   */
  service_preview_title?: string | null;
  /**
   * Compact explanation of the service and its business purpose.
   */
  service_preview_description?: string | null;
  /**
   * Service page image. Not used on Related Services or archive cards.
   */
  service_preview_image?: (number | null) | Media;
  /**
   * Image for archive cards and Related Services. Separate from the Service page image.
   */
  service_card_image?: (number | null) | Media;
  /**
   * In-page heading under the H1. Separate from the internal title, long title and preview title.
   */
  service_content_title?: string | null;
  /**
   * Who the service is for, the problem it addresses, and the intended outcome.
   */
  introduction?: {
    text?: {
      [k: string]: unknown;
    } | null;
    /**
     * Optional second paragraph. Leave empty when the short introduction is enough.
     */
    supportingText?: {
      [k: string]: unknown;
    } | null;
  };
  /**
   * Situations in which this service becomes relevant. Optional.
   */
  clientSituations?:
    | {
        title: string;
        description?: {
          [k: string]: unknown;
        } | null;
        consequence?: {
          [k: string]: unknown;
        } | null;
        recommendedApproach?: {
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Scope items for this Service. Optional.
   */
  serviceScope?:
    | {
        title: string;
        description?: {
          [k: string]: unknown;
        } | null;
        deliverables?: {
          [k: string]: unknown;
        } | null;
        approach?: {
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Process steps. Typically 4–8, with no required count.
   */
  processSteps?:
    | {
        /**
         * Optional. The frontend uses the list order when this is empty.
         */
        stepNumber?: number | null;
        title: string;
        description?: {
          [k: string]: unknown;
        } | null;
        duration?: string | null;
        deliverable?: {
          [k: string]: unknown;
        } | null;
        clientInvolvement?: {
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  /**
   * How a new client can start. All fields are optional and editable per Service.
   */
  entryOffer?: {
    title?: string | null;
    description?: {
      [k: string]: unknown;
    } | null;
    includes?: {
      [k: string]: unknown;
    } | null;
    /**
     * Free-form, e.g. "2–4 weeks". Not a global price list.
     */
    duration?: string | null;
    deliverables?: {
      [k: string]: unknown;
    } | null;
    /**
     * Optional. Leave empty when price is not published.
     */
    price?: string | null;
    ctaLabel?: string | null;
    ctaUrl?: string | null;
    nextStep?: {
      [k: string]: unknown;
    } | null;
  };
  workingFormat?: {
    /**
     * Add only the formats that apply to this Service.
     */
    formats?:
      | {
          format?: ('initial_project' | 'ongoing_monthly' | 'campaign') | null;
          duration?: ('one_time_project' | '1_month' | '3_months' | '6_months' | '1_year' | 'ongoing') | null;
          description?: {
            [k: string]: unknown;
          } | null;
          id?: string | null;
        }[]
      | null;
    minimumEngagement?: ('one_time_project' | '1_month' | '3_months' | '6_months' | '1_year' | 'ongoing') | null;
    /**
     * Optional, e.g. "Weekly working sessions".
     */
    frequency?: string | null;
  };
  /**
   * Descriptive outcomes. Do not invent numeric guarantees.
   */
  expectedOutcomes?:
    | {
        title: string;
        description?: {
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Existing Case Study collection. Preview title, text and image come from each case.
   */
  relatedCaseStudies?: (number | CaseStudy)[] | null;
  /**
   * Same proof-quote shape as Case Study. Separate from FAQ and from the optional Comments layout block.
   */
  clientTestimonial?: {
    quote?: {
      [k: string]: unknown;
    } | null;
    author?: string | null;
    position?: string | null;
    company?: string | null;
  };
  /**
   * Same question/answer pattern as Case Study FAQ. Stored on the Service, not as a separate FAQ collection.
   */
  faq?: {
    /**
     * Section heading. Falls back to a generic heading when empty.
     */
    title?: string | null;
    intro?: {
      [k: string]: unknown;
    } | null;
    /**
     * Typically 5–15 questions. No required count.
     */
    items?:
      | {
          question: string;
          answer: {
            [k: string]: unknown;
          };
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Optional Service-to-Service links. The current Service is excluded.
   */
  relatedServices?: (number | Service)[] | null;
  /**
   * Optional extra blocks (gallery, comments, CTA). Structured sections above do not require this.
   */
  layout?:
    | (
        | ContentBlock
        | ServiceGalleryBlock
        | ServiceCommentsBlock
        | CallToActionBlock
        | MediaBlock
        | ArchiveBlock
        | CodeBlock
      )[]
    | null;
  /**
   * Existing 4D site taxonomy (Services, Industrial, Solutions, Technology). No separate Service category collection.
   */
  site_categories?: (number | SiteCategory)[] | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  /**
   * Display this Service in featured listings.
   */
  featured?: boolean | null;
  /**
   * Lower numbers appear first in the Services archive.
   */
  displayOrder?: number | null;
  publishedAt?: string | null;
  authors?: (number | User)[] | null;
  populatedAuthors?:
    | {
        id?: string | null;
        name?: string | null;
      }[]
    | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ServiceGalleryBlock".
 */
export interface ServiceGalleryBlock {
  service_gallery_title?: string | null;
  /**
   * Up to 20 images from the existing Media collection.
   */
  service_gallery_images?: (number | Media)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'svcGallery';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ServiceCommentsBlock".
 */
export interface ServiceCommentsBlock {
  /**
   * Section heading. Falls back to "Discussion" when empty.
   */
  service_comment_title?: string | null;
  service_comment_text?: {
    [k: string]: unknown;
  } | null;
  comments?:
    | {
        author: string;
        role?: string | null;
        date?: string | null;
        depth?: number | null;
        isExpert?: boolean | null;
        body: {
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'svcComments';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  /**
   * Internal document title. Same Payload title field as Post and Case Study.
   */
  title: string;
  /**
   * Longer editorial/SEO title, same role as Post Long Title and Case Study Long Title.
   */
  testimonialLongTitle: string;
  /**
   * In-page heading. Separate from the internal title, long title and preview title.
   */
  testimonialContentTitle?: string | null;
  /**
   * Short title for cards, sliders and related lists. Not the page H1.
   */
  testimonialPreviewTitle?: string | null;
  /**
   * Compact card text. Independent from the full testimonial; not auto-filled from it.
   */
  testimonialPreviewDescription?: string | null;
  /**
   * Existing Media collection. Portrait, company or project image. Optional.
   */
  testimonialPreviewImage?: (number | null) | Media;
  /**
   * Authentic client statement. Do not rewrite or invent wording.
   */
  testimonial: {
    [k: string]: unknown;
  };
  clientName?: string | null;
  clientPosition?: string | null;
  clientCompany?: string | null;
  clientCompanyWebsite?: string | null;
  clientLocation?: string | null;
  projectContext?: string | null;
  /**
   * Existing Services collection. Optional.
   */
  service?: (number | null) | Service;
  /**
   * Existing Case Study collection. Optional.
   */
  caseStudy?: (number | null) | CaseStudy;
  testimonialType?: ('client' | 'project' | 'service' | 'general') | null;
  /**
   * Existing 4D site taxonomy. No separate Testimonial category collection.
   */
  site_categories?: (number | SiteCategory)[] | null;
  sourceType?: ('direct' | 'email' | 'website' | 'google' | 'linkedin' | 'other') | null;
  sourceUrl?: string | null;
  /**
   * Never set automatically.
   */
  verified?: boolean | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  /**
   * When enabled, this Testimonial can appear in the homepage testimonials block.
   */
  featured?: boolean | null;
  /**
   * Date of the original statement. Separate from createdAt.
   */
  testimonialDate?: string | null;
  /**
   * Optional. Leave empty when there is no rating. Do not default to 5.
   */
  rating?: ('1' | '2' | '3' | '4' | '5') | null;
  publishedAt?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * You will need to rebuild the website when changing this field.
   */
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null)
      | ({
          relationTo: 'case-studies';
          value: number | CaseStudy;
        } | null)
      | ({
          relationTo: 'services';
          value: number | Service;
        } | null)
      | ({
          relationTo: 'testimonials';
          value: number | Testimonial;
        } | null);
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: number;
  title?: string | null;
  priority?: number | null;
  doc: {
    relationTo: 'posts';
    value: number | Post;
  };
  slug?: string | null;
  primary_category_slug?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  categories?:
    | {
        relationTo?: string | null;
        categoryID?: string | null;
        title?: string | null;
        slug?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'case-studies';
        value: number | CaseStudy;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'case-study-categories';
        value: number | CaseStudyCategory;
      } | null)
    | ({
        relationTo: 'site-categories';
        value: number | SiteCategory;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'search';
        value: number | Search;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: number | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  pageLongTitle?: T;
  hero?:
    | T
    | {
        type?: T;
        richText?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                    appearance?: T;
                  };
              id?: T;
            };
        media?: T;
      };
  layout?:
    | T
    | {
        cta?: T | CallToActionBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        archive?: T | ArchiveBlockSelect<T>;
        formBlock?: T | FormBlockSelect<T>;
        pagePreviewBlock?: T | PagePreviewBlockSelect<T>;
        code?: T | CodeBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock_select".
 */
export interface CallToActionBlockSelect<T extends boolean = true> {
  richText?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock_select".
 */
export interface ContentBlockSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        size?: T;
        richText?: T;
        enableLink?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock_select".
 */
export interface MediaBlockSelect<T extends boolean = true> {
  media?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock_select".
 */
export interface ArchiveBlockSelect<T extends boolean = true> {
  introContent?: T;
  populateBy?: T;
  relationTo?: T;
  categories?: T;
  limit?: T;
  selectedDocs?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock_select".
 */
export interface FormBlockSelect<T extends boolean = true> {
  form?: T;
  enableIntro?: T;
  introContent?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PagePreviewBlock_select".
 */
export interface PagePreviewBlockSelect<T extends boolean = true> {
  pagePreviewTitle?: T;
  pagePreviewText?: T;
  pagePreviewImage?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeBlock_select".
 */
export interface CodeBlockSelect<T extends boolean = true> {
  language?: T;
  code?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  postLongTitle?: T;
  layout?:
    | T
    | {
        postPreviewBlock?: T | PostPreviewBlockSelect<T>;
        postContentBlock?: T | PostContentBlockSelect<T>;
        postContentTitleBlock?: T | PostContentTitleBlockSelect<T>;
        postVideoBlock?: T | PostVideoBlockSelect<T>;
        postGalleryBlock?: T | PostGalleryBlockSelect<T>;
        postCommentsBlock?: T | PostCommentsBlockSelect<T>;
        postFAQBlock?: T | PostFAQBlockSelect<T>;
        code?: T | CodeBlockSelect<T>;
        cta?: T | CallToActionBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        archive?: T | ArchiveBlockSelect<T>;
      };
  hero?:
    | T
    | {
        type?: T;
        richText?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                    appearance?: T;
                  };
              id?: T;
            };
        media?: T;
      };
  relatedPosts?: T;
  primary_category?: T;
  categories?: T;
  site_categories?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  authors?: T;
  populatedAuthors?:
    | T
    | {
        id?: T;
        name?: T;
      };
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PostPreviewBlock_select".
 */
export interface PostPreviewBlockSelect<T extends boolean = true> {
  postPreviewTitle?: T;
  postPreviewText?: T;
  postPreviewImage?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PostContentBlock_select".
 */
export interface PostContentBlockSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        size?: T;
        richText?: T;
        enableLink?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PostContentTitleBlock_select".
 */
export interface PostContentTitleBlockSelect<T extends boolean = true> {
  postContentTitle?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PostVideoBlock_select".
 */
export interface PostVideoBlockSelect<T extends boolean = true> {
  postVideoTitle?: T;
  postVideoDescription?: T;
  postVideoCode?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PostGalleryBlock_select".
 */
export interface PostGalleryBlockSelect<T extends boolean = true> {
  postGalleryTitle?: T;
  postGalleryImages?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PostCommentsBlock_select".
 */
export interface PostCommentsBlockSelect<T extends boolean = true> {
  postCommentTitle?: T;
  postCommentText?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PostFAQBlock_select".
 */
export interface PostFAQBlockSelect<T extends boolean = true> {
  postFAQTitle?: T;
  postFAQText?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies_select".
 */
export interface CaseStudiesSelect<T extends boolean = true> {
  title?: T;
  case_study_long_title?: T;
  layout?:
    | T
    | {
        csPreview?: T | CaseStudyPreviewBlockSelect<T>;
        csContent?: T | CaseStudyContentBlockSelect<T>;
        csContentTitle?: T | CaseStudyContentTitleBlockSelect<T>;
        csVideo?: T | CaseStudyVideoBlockSelect<T>;
        csGallery?: T | CaseStudyGalleryBlockSelect<T>;
        csComments?: T | CaseStudyCommentsBlockSelect<T>;
        csFAQ?: T | CaseStudyFAQBlockSelect<T>;
        code?: T | CodeBlockSelect<T>;
        cta?: T | CallToActionBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        archive?: T | ArchiveBlockSelect<T>;
      };
  company_logo?: T;
  manufacturingProfile?:
    | T
    | {
        productionCapabilities?: T;
        products?: T;
        materials?: T;
        applications?: T;
      };
  businessChallenge?:
    | T
    | {
        initialState?: T;
        challenge?: T;
        goals?: T;
      };
  nicheSegmentation?:
    | T
    | {
        name?: T;
        description?: T;
        marketingApproach?: T;
        id?: T;
      };
  digitalEcosystem?: T;
  websiteArchitecture?: T;
  semanticArchitecture?: T;
  marketingStrategy?:
    | T
    | {
        seoAndContentStrategy?: T;
        leadGenMechanism?: T;
        paidAdvertising?:
          | T
          | {
              channel?: T;
              strategy?: T;
              campaignStructure?: T;
              results?: T;
              id?: T;
            };
        socialMedia?:
          | T
          | {
              channel?: T;
              strategy?: T;
              content?: T;
              results?: T;
              id?: T;
            };
      };
  aiSearchOptimization?:
    | T
    | {
        brandAuthorityAndTrust?: T;
        entityAndGeoStructure?: T;
      };
  implementationProcess?: T;
  timeline?:
    | T
    | {
        period?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  resultsSummary?: T;
  metrics?:
    | T
    | {
        value?: T;
        label?: T;
        description?: T;
        id?: T;
      };
  projectsShowcase?:
    | T
    | {
        projectName?: T;
        description?: T;
        image?: T;
        url?: T;
        id?: T;
      };
  expertInsight?: T;
  clientTestimonial?:
    | T
    | {
        quote?: T;
        author?: T;
        position?: T;
        company?: T;
      };
  hero?:
    | T
    | {
        type?: T;
        richText?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                    appearance?: T;
                  };
              id?: T;
            };
        media?: T;
      };
  relatedCaseStudies?: T;
  primary_case_study_category?: T;
  case_study_categories?: T;
  site_categories?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  featured?: T;
  displayOrder?: T;
  duration?: T;
  publishedAt?: T;
  authors?: T;
  populatedAuthors?:
    | T
    | {
        id?: T;
        name?: T;
      };
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CaseStudyPreviewBlock_select".
 */
export interface CaseStudyPreviewBlockSelect<T extends boolean = true> {
  case_study_preview_title?: T;
  case_study_preview_text?: T;
  case_study_preview_image?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CaseStudyContentBlock_select".
 */
export interface CaseStudyContentBlockSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        size?: T;
        richText?: T;
        enableLink?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CaseStudyContentTitleBlock_select".
 */
export interface CaseStudyContentTitleBlockSelect<T extends boolean = true> {
  case_study_content_title?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CaseStudyVideoBlock_select".
 */
export interface CaseStudyVideoBlockSelect<T extends boolean = true> {
  case_study_video_title?: T;
  case_study_video_description?: T;
  case_study_video_code?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CaseStudyGalleryBlock_select".
 */
export interface CaseStudyGalleryBlockSelect<T extends boolean = true> {
  case_study_gallery_title?: T;
  case_study_gallery_images?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CaseStudyCommentsBlock_select".
 */
export interface CaseStudyCommentsBlockSelect<T extends boolean = true> {
  case_study_comment_title?: T;
  case_study_comment_text?: T;
  comments?:
    | T
    | {
        author?: T;
        role?: T;
        date?: T;
        depth?: T;
        isExpert?: T;
        body?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CaseStudyFAQBlock_select".
 */
export interface CaseStudyFAQBlockSelect<T extends boolean = true> {
  case_study_faq_title?: T;
  case_study_faq_text?: T;
  items?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  service_long_title?: T;
  service_preview_title?: T;
  service_preview_description?: T;
  service_preview_image?: T;
  service_card_image?: T;
  service_content_title?: T;
  introduction?:
    | T
    | {
        text?: T;
        supportingText?: T;
      };
  clientSituations?:
    | T
    | {
        title?: T;
        description?: T;
        consequence?: T;
        recommendedApproach?: T;
        id?: T;
      };
  serviceScope?:
    | T
    | {
        title?: T;
        description?: T;
        deliverables?: T;
        approach?: T;
        id?: T;
      };
  processSteps?:
    | T
    | {
        stepNumber?: T;
        title?: T;
        description?: T;
        duration?: T;
        deliverable?: T;
        clientInvolvement?: T;
        id?: T;
      };
  entryOffer?:
    | T
    | {
        title?: T;
        description?: T;
        includes?: T;
        duration?: T;
        deliverables?: T;
        price?: T;
        ctaLabel?: T;
        ctaUrl?: T;
        nextStep?: T;
      };
  workingFormat?:
    | T
    | {
        formats?:
          | T
          | {
              format?: T;
              duration?: T;
              description?: T;
              id?: T;
            };
        minimumEngagement?: T;
        frequency?: T;
      };
  expectedOutcomes?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  relatedCaseStudies?: T;
  clientTestimonial?:
    | T
    | {
        quote?: T;
        author?: T;
        position?: T;
        company?: T;
      };
  faq?:
    | T
    | {
        title?: T;
        intro?: T;
        items?:
          | T
          | {
              question?: T;
              answer?: T;
              id?: T;
            };
      };
  relatedServices?: T;
  layout?:
    | T
    | {
        content?: T | ContentBlockSelect<T>;
        svcGallery?: T | ServiceGalleryBlockSelect<T>;
        svcComments?: T | ServiceCommentsBlockSelect<T>;
        cta?: T | CallToActionBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        archive?: T | ArchiveBlockSelect<T>;
        code?: T | CodeBlockSelect<T>;
      };
  site_categories?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  featured?: T;
  displayOrder?: T;
  publishedAt?: T;
  authors?: T;
  populatedAuthors?:
    | T
    | {
        id?: T;
        name?: T;
      };
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ServiceGalleryBlock_select".
 */
export interface ServiceGalleryBlockSelect<T extends boolean = true> {
  service_gallery_title?: T;
  service_gallery_images?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ServiceCommentsBlock_select".
 */
export interface ServiceCommentsBlockSelect<T extends boolean = true> {
  service_comment_title?: T;
  service_comment_text?: T;
  comments?:
    | T
    | {
        author?: T;
        role?: T;
        date?: T;
        depth?: T;
        isExpert?: T;
        body?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  title?: T;
  testimonialLongTitle?: T;
  testimonialContentTitle?: T;
  testimonialPreviewTitle?: T;
  testimonialPreviewDescription?: T;
  testimonialPreviewImage?: T;
  testimonial?: T;
  clientName?: T;
  clientPosition?: T;
  clientCompany?: T;
  clientCompanyWebsite?: T;
  clientLocation?: T;
  projectContext?: T;
  service?: T;
  caseStudy?: T;
  testimonialType?: T;
  site_categories?: T;
  sourceType?: T;
  sourceUrl?: T;
  verified?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  featured?: T;
  testimonialDate?: T;
  rating?: T;
  publishedAt?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlarge?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  category_long_title?: T;
  category_description?: T;
  category_image?: T;
  relatedPosts?: T;
  layout?:
    | T
    | {
        cta?: T | CallToActionBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        archive?: T | ArchiveBlockSelect<T>;
        formBlock?: T | FormBlockSelect<T>;
        code?: T | CodeBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  generateSlug?: T;
  slug?: T;
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-study-categories_select".
 */
export interface CaseStudyCategoriesSelect<T extends boolean = true> {
  title?: T;
  case_study_long_title?: T;
  case_study_description?: T;
  case_study_image?: T;
  relatedCaseStudies?: T;
  layout?:
    | T
    | {
        cta?: T | CallToActionBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        archive?: T | ArchiveBlockSelect<T>;
        formBlock?: T | FormBlockSelect<T>;
        code?: T | CodeBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  generateSlug?: T;
  slug?: T;
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-categories_select".
 */
export interface SiteCategoriesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  slug?: T;
  primary_category_slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  categories?:
    | T
    | {
        relationTo?: T;
        categoryID?: T;
        title?: T;
        slug?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  folderType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Title and SEO for the /case-studies listing page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies-archive".
 */
export interface CaseStudiesArchive {
  id: number;
  /**
   * Internal page title, used for navigation and admin. Not rendered as a heading.
   */
  title?: string | null;
  /**
   * Rendered as the H1 on /case-studies.
   */
  longTitle?: string | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies-archive_select".
 */
export interface CaseStudiesArchiveSelect<T extends boolean = true> {
  title?: T;
  longTitle?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null)
      | ({
          relationTo: 'case-studies';
          value: number | CaseStudy;
        } | null)
      | ({
          relationTo: 'services';
          value: number | Service;
        } | null)
      | ({
          relationTo: 'testimonials';
          value: number | Testimonial;
        } | null);
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}